"Bazel provider for resolving a `package:...` URI."

DartPackageResolutionInfo = provider(
    """\
Provider for how to resolve a `package:{name}` URI to a local file.

This format should rarely be defined automatically, and should instead be
generated by a tool, such as one that reads `package_config.json` files.

See https://dart.dev/go/dot-packages-deprecation.
""",
    # Where possible, use the exact same field names as in the specification.
    #
    # The only change is to use underscores instead of camelCase.
    fields = {
        "name": "Package name.",
        "root": "A path to the root of the package.",
        "path": "A relative path from the root to a sub-directory. Optional.",
        "version": "A Dart language version (i.e. `1.2`). Optional.",
    },
)
