name: Blocking Issues

on: 
  issues:
    types: [opened, edited, deleted, transferred, closed, reopened]
  pull_request_target: 
    types: [opened, edited, closed, reopened]
  schedule:
    # On the hour run.
    - cron: '0 * * * *'

jobs: 
  blocking_issues: 
    runs-on: ubuntu-latest
    name: Checks for blocking issues
    
    steps: 
      - uses: Levi-Lesches/blocking-issues@v2
