name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Every day at 11:09 UTC.
    - cron: '9 11 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rules:
    name: Rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: p0deje/setup-bazel@0.8.0
        with:
          # Better config for CI.
          bazelrc: ./.github/workflows/.ci.bazelrc
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - run: bazel run :buildifier.check
      - run: bazel test ...

  examples_posix_x64:
    name: "${{ matrix.os == 'ubuntu' && 'linux-x64' || 'mac-x64' }}: examples"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu # linux-x64
          - macos # mac-x64
    defaults:
      run:
        working-directory: examples/simple
    steps:
      - uses: actions/checkout@v4
      - uses: p0deje/setup-bazel@0.8.0
        with:
          # Better config for CI.
          bazelrc: ./.github/workflows/.ci.bazelrc
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: examples/simple/MODULE.bazel
      - run: bazel build ...

  examples_macos_arm64:
    name: "macos-arm64: examples"
    runs-on: macos-14-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: examples/simple
    # Only run this on post-merge. It's too slow to run on every push.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: p0deje/setup-bazel@0.8.0
        with:
          # Better config for CI.
          bazelrc: ./.github/workflows/.ci.bazelrc
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: examples/simple/MODULE.bazel
      - run: bazel build ...
